

straight_examples = [
        "asmr", 
        "swag", 
        "fitness", 
        "prank", 
        "whisper", 
        "gay", 
        "lgbt", 
        "comedy", 
        "funny", 
        "cute", 
        "dance", 
        "fun", 
        "art", 
        "love", 
        "fashion", 
        "bts", 
        "couple", 
        "canada", 
        "boys", 
        "kpop", 
        "toronto", 
        "korean", 
        "food", 
        "mixed", 
        "culture", 
        "frat"
    ]
alt_examples = [
        "Trees", 
        "Diesel", 
        "Donuts", 
        "Watermelon", 
        "Fruit", 
        "Zoo", 
        "techtok", 
        "cemetery", 
        "italian", 
        "cars", 
        "sealife", 
        "doggo", 
        "painting", 
        "diy", 
        "basketball", 
        "backpack", 
        "magic", 
        "chef", 
        "swimming", 
        "gaming", 
        "valorant"
    ]

cringe_example = [
    "asmr",
    "cringe",
    "funny",
    "memes",
    "edgy",
    "gaming",
    "valorant",
    "kpop",
    "prank",
    "love",
    "couple",
    "dating",
    "girlfriend",
    "boyfriend",
    "gay",
    "sister",
    "canada"
]

based_example = [
    "culture",
    "technology",
    "fashion",
    "fitness",
    "gym",
    "food",
    "cooking",
    "fruit",
    "travel",
    "music",
    "hiphop",
    "science",
    "physics",
    "japan",
    "wholesome",
    "college",
    "school"
]

educational_example = [
    "canada",
    "lakes", 
    "school",
    "textbook",
    "math",
    "science",
    "calculus",
    "college",
    "university",
    "history",
    "teacher",
    "phd",
    "education",
    "learn",
    "video"

]

entertainment_example = [
    "movie",
    "fashion",
    "tv",
    "kdrama",
    "drama",
    "entertainment",
    "funny",
    "tiktok",
    "hype",
    "dance",
    "skit",
    "comedy",
    "shows",
    "laugh",
    "food",
    "travel"
]